# Generated by Django 5.0.1 on 2024-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_field', models.CharField(max_length=100)),
                ('specific_field', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
