# Generated by Django 5.0.1 on 2024-02-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0002_mysubmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='MySubModel',
        ),
        migrations.CreateModel(
            name='SubModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='log_app.basemodel')),
                ('specific_field', models.IntegerField()),
            ],
            bases=('log_app.basemodel',),
        ),
    ]
