# Generated by Django 5.0.1 on 2024-02-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0003_basemodel_delete_mysubmodel_submodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submodel',
            name='basemodel_ptr',
        ),
        migrations.RenameField(
            model_name='page_data',
            old_name='username',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='page_data',
            old_name='password',
            new_name='name',
        ),
        migrations.AddField(
            model_name='page_data',
            name='bones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page_data',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
        migrations.DeleteModel(
            name='SubModel',
        ),
    ]
